RTK Correction topic exposed on microRTPS
tiiuae/px4_ros_com pull request #40
Opened 2022-09-08 13:27 UTC by aravindraja93

_gps_inject_data_ Topic is exposed on microRTPS bridge enabling the use of RTK base corrections

2022-09-08 15:18 UTC, jlaitine requested changes

2022-09-08 15:18 UTC, jlaitine commented on templates/urtps_bridge_topics.yaml
> +    recieve: true
There is a typo. It is "receive"

2022-09-08 15:50 UTC, aravindraja93 commented on templates/urtps_bridge_topics.yaml
> +    recieve: true
ahh, didn't notice that. Fixed now :)

2022-09-08 18:49 UTC, jlaitine commented
Please make these into one commit (squash the commits and force-push the pr)  . Looks cleaner in git.history afterwards :) Then it is good!

2022-09-09 05:55 UTC, jlaitine approved these changes

2022-09-09 05:55 UTC, jlaitine approved these changes

2022-09-09 05:59 UTC, merged