Use reliability:BEST_EFFORT and durability:VOLATILE
tiiuae/px4_ros_com pull request #7
Opened 2021-04-22 11:30 UTC by jnippula

2021-04-22 11:47 UTC, jlaitine approved these changes

2021-04-22 11:48 UTC, jlaitine commented
this is fine for us; maybe we should also add a command line argument for this? then we could also upstream it

2021-04-22 11:56 UTC, jlaitine requested changes

2021-04-22 11:56 UTC, jlaitine commented on templates/Publisher.cpp.em
> +    Wparam.qos.m_reliability.kind = eprosima::fastdds::dds::BEST_EFFORT_RELIABILITY_QOS;
The namespace is already included in Publisher.h.em, (using namespace eprosima::fastdds::dds;) so probably it is not entirely correct to specify the full namespace here.

In older version of the fastrtps this qos setting is in namespace eprosima::fastrtps::rtps

2021-04-23 14:22 UTC, jnippula commented
New PR created, so this is closed.

2021-04-23 14:22 UTC, closed without merging